### ISSUE TITLE
Penyesuaian data yang dikirim ke PBB melalui OpenSID untuk kebutuhan subject pajak 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-opensid-api#1]
Issue ini berkaitan dengan https://github.com/OpenSID/wiki-pbb/issues/97  untuk melengkapin penambahan field NIK pada subject pajak.

**Comment by FirlianiF** [comment]
PR https://github.com/OpenSID/opensid-laravel/pull/34
