### ISSUE TITLE
Buat data dummy untuk unit testing

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-opensid-api#10]
1. Perlu dibuat terkait kumpulan data dummy agar unit testing menjadi konsisten.

**Comment by scqolbu24** [comment]
sudah dibuatkan database pengetesan untuk unit testing dan tekah dibuatkan panduannya
di https://panduan.opendesa.id/id/opensid-api/dokumentasi#siapkan-database-dummy

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://panduan.opendesa.id/id/opensid-api/dokumentasi#siapkan-database-dummy
