### ISSUE TITLE
Spesifikasi API Mobile Admin perlu dibuat collection API di postman

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-opensid-api#11]
Sesuaikan Daftar API yang digunakan dalam Mobile Admin ke daftar  collection postmen.

**Comment by scqolbu24** [comment]
Berikut Collection OpenSID API 
[OpenSID API.postman_collection.json](https://github.com/OpenSID/wiki-opensid-api/files/12867251/OpenSID.API.postman_collection.json)

Berikut Environment OpenSID API
[OpenSID API Team (sarwono) local.postman_environment.json](https://github.com/OpenSID/wiki-opensid-api/files/12867269/OpenSID.API.Team.sarwono.local.postman_environment.json)
