### ISSUE TITLE
Perbaiki form surat RTF menjadi null setelah perubahan select manual dan otomatis

### ISSUE THREAD

**Issue by yogiperdana** [OpenSID/wiki-opensid-api#6]
- [x] Surat RTF dapat ditampilkan (mobile) 
- [x] Surat kode isian manual dapat di tampilkan (mobile) 
- [x] Surat kode isi otomatis dapat ditampilkan (mobile) 
- [x] Surat dapat dicetak di permohonan surat admin (OpenSID)

**Comment by apidong** [comment]
diperbaiki di https://github.com/OpenSID/opensid-laravel/pull/125
